### ISSUE TITLE
swagger ui cannot access swagger.json with nginx

### ISSUE THREAD

**Issue by ijalalfrz** [python-restx/flask-restx#230]
so i have nginx configuration like this for my docker-compose

```
upstream video_converter {
    server web:5000;
}

server {

    listen 8000;

    location / {
        proxy_pass http://video_converter;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

}
```
and docker compose like  this
```

version: '3.7'

services:
  web:
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 --worker-connections 5000 --timeout 6000 manage:app
    volumes:
      - ./:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.1
    restart: unless-stopped
    command: mongod
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    volumes:
      - mongodbdata:/data/db

  nginx:
    build: ./nginx
    ports:
      - 5001:8000
    depends_on:
      - web

volumes:
  mongodbdata:  
```

everytime i access localhost:5001/api/v1 (swagger doc) it successfully load the UI but there is an error:
`NetworkError when attempting to fetch resource. http://localhost/api/v1/swagger.json` because it shows json for the UI

the flask restx should request to `http://localhost:5001/api/v1/swagger.json`

anyone can help me?
